version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vacation_db
    environment:
      POSTGRES_DB: vacation_management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vacation_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vacation_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vacation_management
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      JWT_SECRET: your-secret-key-change-in-production-min-256-bits
      JWT_EXPIRATION: 86400000
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - vacation_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vacation_frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - vacation_network

volumes:
  postgres_data:

networks:
  vacation_network:
    driver: bridge